language: cpp
before_script:
- pip3 install conan
script:
- conan install --build=missing -s build_type=Release -s compiler.cppstd=17 .
- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -X PUT -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushiwin:$BINTRAY_API_KEY "https://api.bintray.com/content/shiwin/otus/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=wheezy;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    branch: main
